PACKAGE_NAME="rt2800usb"
PACKAGE_VERSION="1.0"
CLEAN="make clean"
MAKE[0]="make KVER=$kernelver"
BUILT_MODULE_NAME[0]="rt2x00lib"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/wireless/ralink/rt2x00"
BUILT_MODULE_NAME[1]="rt2x00usb"
BUILT_MODULE_LOCATION[1]="."
DEST_MODULE_LOCATION[1]="/kernel/drivers/net/wireless/ralink/rt2x00"
BUILT_MODULE_NAME[2]="rt2800lib"
BUILT_MODULE_LOCATION[2]="."
DEST_MODULE_LOCATION[2]="/kernel/drivers/net/wireless/ralink/rt2x00"
BUILT_MODULE_NAME[3]="rt2800usb"
BUILT_MODULE_LOCATION[3]="."
DEST_MODULE_LOCATION[3]="/kernel/drivers/net/wireless/ralink/rt2x00"
AUTOINSTALL="yes"
